language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:maxmind/ppa
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf
  - sudo apt-get install -y libmaxminddb0 libmaxminddb-dev mmdb-bin libyaml-dev
before_script:
  - rake setup
script:
  - rake test
